platform :ios, '7.0'

target 'ZKDemoPro' do
pod 'AFNetworking', '~> 3.0'
pod 'Masonry'
pod 'SDWebImage', '~>3.8'
pod 'AMap3DMap'  #3D地图 SDK
pod 'AMapSearch'
pod 'AMapLocation'
pod 'YYKit'
pod 'WebViewJavascriptBridge', '~> 5.0'
end
